### ISSUE TITLE
分离http，websocket

### ISSUE THREAD

**Issue by cole-dda** [wentch/redkale#1]
可以把http，websocket分离出来，作为一个独立的库吗？不要作为一个框架，可以很方便的嵌入使用。因为传统的基于servlet的框架太繁琐了。

**Comment by wentch** [comment]
@cole-dda redkale本身就是很小巧的，不到1.5M，redkale并不是基于传统servlet规范，而是自定义的， 结构上已经是分离的， net组件只依赖util与convert包，其他包可以删除，但是webscoket需要分布式功能， 不然部署两个进程，都连接websocket，其中一个无法知道另一个进程上有多少用户处于连接状态。
